const qs=(s,r=document)=>r.querySelector(s);const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const state={filter:'all',query:'',favorites:new Set(JSON.parse(localStorage.getItem('d3dps-favorites')||'[]')),cart:JSON.parse(localStorage.getItem('d3dps-cart')||'[]')};
const cards=qsa('.product-card');
function save(){localStorage.setItem('d3dps-favorites',JSON.stringify([...state.favorites]));localStorage.setItem('d3dps-cart',JSON.stringify(state.cart));}
function renderCards(){cards.forEach(card=>{const cats=card.dataset.category;const name=card.dataset.name.toLowerCase();const matchFilter=state.filter==='all'||(state.filter==='favorites'?state.favorites.has(card.dataset.id):cats.includes(state.filter));const matchQuery=name.includes(state.query)||cats.includes(state.query);card.hidden=!(matchFilter&&matchQuery);const fav=qs('.favorite-button',card);fav.classList.toggle('active',state.favorites.has(card.dataset.id));fav.textContent=state.favorites.has(card.dataset.id)?'♥':'♡';const add=qs('.add-button',card);const inCart=state.cart.some(x=>x.id===card.dataset.id);add.classList.toggle('added',inCart);add.textContent=inCart?'Added':'Add to inquiry'});qs('#no-results').hidden=cards.some(c=>!c.hidden)}
function renderCart(){qs('#cart-count').textContent=state.cart.length;const wrap=qs('#cart-items');wrap.innerHTML=state.cart.length?state.cart.map(item=>`<div class="cart-item"><div><strong>${item.name}</strong><br><small>${item.price}</small></div><button type="button" data-remove="${item.id}">Remove</button></div>`).join(''):'<p>Your inquiry list is empty.</p>';qsa('[data-remove]',wrap).forEach(b=>b.addEventListener('click',()=>{state.cart=state.cart.filter(x=>x.id!==b.dataset.remove);save();renderCart();renderCards()}))}
qsa('.filter').forEach(btn=>btn.addEventListener('click',()=>{qsa('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.filter=btn.dataset.filter;renderCards()}));
qsa('[data-jump-filter]').forEach(link=>link.addEventListener('click',()=>{const f=link.dataset.jumpFilter;const btn=qs(`[data-filter="${f}"]`);if(btn){qsa('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.filter=f;renderCards()}}));
function applySearch(value){state.query=value.trim().toLowerCase();qs('#product-search').value=value;renderCards()}
qs('#product-search').addEventListener('input',e=>applySearch(e.target.value));qs('#header-search').addEventListener('keydown',e=>{if(e.key==='Enter'){applySearch(e.target.value);location.hash='products'}});
cards.forEach(card=>{qs('.favorite-button',card).addEventListener('click',()=>{state.favorites.has(card.dataset.id)?state.favorites.delete(card.dataset.id):state.favorites.add(card.dataset.id);save();renderCards()});qs('.add-button',card).addEventListener('click',()=>{const existing=state.cart.some(x=>x.id===card.dataset.id);if(existing)state.cart=state.cart.filter(x=>x.id!==card.dataset.id);else state.cart.push({id:card.dataset.id,name:card.dataset.name,price:card.dataset.price});save();renderCart();renderCards()})});
const panel=qs('#cart-panel'),scrim=qs('#cart-scrim');function openCart(open){panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open));qs('#cart-toggle').setAttribute('aria-expanded',String(open));scrim.hidden=!open}qs('#cart-toggle').addEventListener('click',()=>openCart(true));qs('#cart-close').addEventListener('click',()=>openCart(false));scrim.addEventListener('click',()=>openCart(false));
qs('#cart-clear').addEventListener('click',()=>{state.cart=[];save();renderCart();renderCards()});qs('#cart-email').addEventListener('click',()=>{if(!state.cart.length)return;const lines=state.cart.map(x=>`- ${x.name} (${x.price})`).join('\n');location.href=`mailto:D3DPSYYC@gmail.com?subject=${encodeURIComponent('D3DPS product inquiry')}&body=${encodeURIComponent('Hi D3DPS,\n\nI would like a quote for:\n'+lines+'\n\nPreferred colour(s):\nQuantity:\nAdditional details:\n')}`});
const storedTheme=localStorage.getItem('d3dps-theme');if(storedTheme)document.documentElement.dataset.theme=storedTheme;qs('#theme-toggle').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('d3dps-theme',next)});
const menu=qs('#main-nav');qs('#menu-toggle').addEventListener('click',e=>{const open=menu.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});qsa('.main-nav a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')));
qs('#quote-form').addEventListener('submit',e=>{e.preventDefault();const name=qs('#name').value.trim(),contact=qs('#contact-info').value.trim(),cat=qs('#quote-category').value,details=qs('#details').value.trim();const body=`Hi D3DPS,\n\nName: ${name}\nContact: ${contact}\nCategory: ${cat}\n\nProject details:\n${details}\n\nI will attach any photos or files before sending.`;location.href=`mailto:D3DPSYYC@gmail.com?subject=${encodeURIComponent('D3DPS quote request — '+cat)}&body=${encodeURIComponent(body)}`});
qs('#year').textContent=new Date().getFullYear();renderCart();renderCards();
